=== JoaoLucas1682/joaolucas1682.github.io/sl1682/v1/schema/SLSchema.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://joaolucas1682.github.io/sl1682/v1/spec/html"
    xmlns="https://joaolucas1682.github.io/sl1682/v1/spec/html" 
elementFormDefault="qualified">
<xs:annotation>
  <xs:documentation>
    XSD Schema for SitesList version 1
    2026-04-02 | joaolucas1682.github.io
  </xs:documentation>
</xs:annotation>

    <xs:element name="SitesList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Metadata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SLVersion" type="xs:string" fixed="v1"/>
                            <xs:element name="DateUpdated" type="xs:date"/>
                            <xs:element name="OrgInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Maintainer" type="xs:string"/>
                                        <xs:element name="Organization" type="xs:string"/>
                                        <xs:element name="OrgSite" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:any minOccurs="0"/>
                        </xs:sequence>
                        <xs:anyAttribute/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Site">
                <xs:complexType>
                  <xs:sequence>
                   <xs:element name="IsRevoked">
                   <xs:simpleType>
                   <xs:restriction base="xs:integer">
                         <xs:minInclusive value="0"/>
                         <xs:maxInclusive value="1"/>
                   </xs:restriction>
                   </xs:simpleType>
                   </xs:element>
                   <xs:element name="Reason">
                   <xs:simpleType>
                   <xs:restriction base="xs:integer">
                         <xs:minInclusive value="0"/>
                         <xs:maxInclusive value="21"/>
                   </xs:restriction>
                   </xs:simpleType>
                   </xs:element>
                  <xs:element name="URL" type="xs:anyURI"/>
                  <xs:element name="TimestampAdded" type="xs:dateTime"/>
                  <xs:any minOccurs="0"/>
                  </xs:sequence>
                  <xs:anyAttribute/>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JoaoLucas1682/joaolucas1682.github.io/sl1682/v1/exmpl/1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<SitesList
xmlns="https://joaolucas1682.github.io/sl1682/v1/doc/html" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://joaolucas1682.github.io/sl1682/v1/doc/html https://joaolucas1682.github.io/sl1682/v1/schema/SLSchema.xsd">
  <Metadata>
  <SLVersion>v1</SLVersion>
  <DateUpdated>2026-04-02</DateUpdated>
  <OrgInfo>
    <Maintainer>BestMaintainer123 </Maintainer>
    <Organization>AnExpert</Organization>
    <OrgSite>https://the.expert.sitex/</OrgSite>
  </OrgInfo>
  </Metadata>
<Site>
<IsRevoked>1</IsRevoked>
<Reason>1</Reason>
<URL>https://badsite.com</URL>
<TimestampAdded>2067-06-07T06:07:00</TimestampAdded>
</Site>
</SitesList>
